title: Site



columns:

  - width: 2/3
    fields:
      sottotitolo:
        type: text
      bio:
        type: textarea
        label: Bio Ocio

  - width: 1/3  
    sections:
      pages:
        type: pages
        label: Pagine
        create: default
        templates:
          - agenda
          - report
          - glossario
          - chi-siamo

  - width: 2/3
    sections:
      report: sections/report

  - width: 1/3  
    sections:
      agenda: sections/agenda


